[package]
name = "asset-rarity"
version.workspace = true
authors.workspace = true
edition = "2021"
description = "Pluggable NFT rarity scoring (Magic Eden statistical, OpenRarity IC)"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
approx = "0.5"
